services:
  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongPass123
      MYSQL_DATABASE: dundermifflin
      MYSQL_USER: dwight
      MYSQL_PASSWORD: BeetsBearbeiten2025!
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect=1", "--mariadbupgrade"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mariadbdata:
